import SwiftUI

struct HomeView: View {
    @EnvironmentObject var store:AppStore; let open:(Route)->Void
    private let cols=[GridItem(.flexible(),spacing:10),GridItem(.flexible(),spacing:10)]
    var body:some View { ScrollView{ VStack(spacing:12){
        HStack{ Button{open(.settings)}label:{Image(systemName:"line.3.horizontal")}; Text("PetLingo").font(.largeTitle.bold()); Spacer(); VStack(alignment:.trailing){Text("Hi, 學習者 👋").bold(); Text("持續學習的每一天都很棒！").font(.caption).foregroundStyle(.secondary)}; Button{open(.settings)}label:{Image(systemName:"bell.fill")} }
        Image("petlingo_home_banner",bundle:.main).resizable().scaledToFill().frame(maxWidth:.infinity).aspectRatio(1.78,contentMode:.fit).clipShape(RoundedRectangle(cornerRadius:24)).shadow(radius:3)
        Button{open(.daily)}label:{ VStack(spacing:8){HStack{Image(systemName:"medal.fill").font(.system(size:36)).foregroundStyle(.orange); VStack(alignment:.leading){Text("今日任務（成人版）").font(.headline).foregroundStyle(.primary);Text("完成 20 題可獲得獎勵！").font(.caption).foregroundStyle(.secondary)};Spacer();Text("\(min(store.todayAnswered,20)) / 20").font(.title2.bold())};ProgressView(value:Double(min(store.todayAnswered,20)),total:20)}.cardStyle(PLColor.yellowSoft)}.buttonStyle(.plain)
        LazyVGrid(columns:cols,spacing:10){ FeatureTile("GEPT 單字學習","初級・中級・中高級","book.fill",PLColor.greenSoft){open(.vocabulary)}; FeatureTile("片語學習","常用片語與例句","bubble.left.and.bubble.right.fill",PLColor.pinkSoft){open(.phrase)}; FeatureTile("測驗練習","單字・文法・克漏字","checkmark.circle.fill",PLColor.purpleSoft){open(.quizSetup)}; FeatureTile("閱讀測驗","文章理解與題組","doc.text.fill",PLColor.blueSoft){open(.reading)}; FeatureTile("聽力練習","英美發音訓練","headphones",PLColor.yellowSoft){open(.listeningSetup)}; FeatureTile("口說測驗","語音辨識與評分","mic.fill",PLColor.pinkSoft){open(.speaking)} }
        HStack(spacing:8){ MiniTool("收藏","\(store.favorites.count) 個","heart.fill"){open(.favorites)}; MiniTool("錯題","\(store.wrongAnswers.count) 題","xmark.circle.fill"){open(.wrong)}; MiniTool("筆記","\(store.notes.count) 則","note.text"){open(.notes)} }
        HStack(spacing:10){ VStack(alignment:.leading,spacing:5){Text("最近學習").bold(); if let s=store.lastSession{Text(s.modeLabel).font(.caption);Text("\(s.score) 分・正確 \(s.correctCount) 題").foregroundStyle(.green).bold();Text(formatTime(s.totalMillis)).font(.caption)}else{Text("尚未完成測驗").foregroundStyle(.secondary)}}.frame(maxWidth:.infinity,alignment:.leading).cardStyle(); VStack(alignment:.leading,spacing:5){Text("今日建議").bold();Text("建議複習").font(.caption);Text("cooperation").bold();Button("立即複習"){open(.phrase)}}.frame(maxWidth:.infinity,alignment:.leading).cardStyle(PLColor.yellowSoft.opacity(0.6)) }
        HStack{VStack(alignment:.leading){Text("連續學習天數").bold();Text("7 天").font(.title.bold());Text("太棒了！繼續加油！").font(.caption)};Spacer();Text("🔥").font(.largeTitle)}.cardStyle()
        HStack{MiniTool("學習分析","能力與表現","chart.bar.fill"){open(.analytics)};MiniTool("學習紀錄","查看歷次紀錄","clock.fill"){open(.history)};MiniTool("設定","音效・顯示","gearshape.fill"){open(.settings)}}
    }.padding(14) }.background(PLColor.background.ignoresSafeArea()).navigationTitle("") }
    func formatTime(_ ms:Int)->String{let sec=ms/1000; return "\(sec/60) 分 \(sec%60) 秒"}
}
struct FeatureTile:View{let t:String,s:String,i:String;let c:Color;let action:()->Void;init(_ t:String,_ s:String,_ i:String,_ c:Color,_ action:@escaping()->Void){self.t=t;self.s=s;self.i=i;self.c=c;self.action=action};var body:some View{Button(action:action){VStack(spacing:8){Image(systemName:i).font(.system(size:36));Text(t).bold().multilineTextAlignment(.center);Text(s).font(.caption).foregroundStyle(.secondary).multilineTextAlignment(.center)}.frame(maxWidth:.infinity,minHeight:112).cardStyle(c)}.buttonStyle(.plain)}}
struct MiniTool:View{let t:String,s:String,i:String;let action:()->Void;init(_ t:String,_ s:String,_ i:String,_ action:@escaping()->Void){self.t=t;self.s=s;self.i=i;self.action=action};var body:some View{Button(action:action){VStack(spacing:4){Image(systemName:i);Text(t).font(.caption.bold());Text(s).font(.caption2).foregroundStyle(.secondary).lineLimit(1)}.frame(maxWidth:.infinity,minHeight:70).cardStyle(Color(.secondarySystemBackground),radius:16)}.buttonStyle(.plain)}}

struct LearningHubView:View{let open:(Route)->Void;var body:some View{ScrollView{VStack(spacing:12){Text("學習中心").font(.largeTitle.bold()).frame(maxWidth:.infinity,alignment:.leading); FeatureTile("GEPT 單字學習","依級別搜尋與收藏","book.fill",PLColor.greenSoft){open(.vocabulary)};FeatureTile("片語學習","50 組常用片語","text.bubble.fill",PLColor.pinkSoft){open(.phrase)};FeatureTile("閱讀練習","8 篇文章題組","doc.text.fill",PLColor.blueSoft){open(.reading)};FeatureTile("筆記本","收藏自己的學習重點","note.text",PLColor.purpleSoft){open(.notes)}}.padding()}}}

struct VocabularyView:View{ @EnvironmentObject var store:AppStore; @EnvironmentObject var speech:SpeechService; @State private var q=""; @State private var level="全部"; var filtered:[Word]{store.words.filter{w in (q.isEmpty || w.english.localizedCaseInsensitiveContains(q) || w.chinese.contains(q)) && (level=="全部" || w.level.contains(level))}}; var body:some View{List{Section{Picker("級別",selection:$level){ForEach(["全部","初級","中級","中高級"],id:\.self){Text($0)}}.pickerStyle(.segmented);TextField("搜尋英文或中文",text:$q).textFieldStyle(.roundedBorder)};ForEach(filtered.prefix(1000)){w in HStack{VStack(alignment:.leading){Text(w.english).font(.headline);Text(w.chinese);if !w.partOfSpeech.isEmpty{Text(w.partOfSpeech).font(.caption).foregroundStyle(.secondary)}};Spacer();Button{speech.speak(w.english,accent:store.settings.accent,rate:store.settings.speechRate)}label:{Image(systemName:"speaker.wave.2.fill")};Button{store.toggleFavorite(w.id)}label:{Image(systemName:store.favorites.contains(w.id) ? "heart.fill":"heart")}}}}.navigationTitle("GEPT 單字學習")}}
struct PhraseView:View{@EnvironmentObject var store:AppStore;@EnvironmentObject var speech:SpeechService;var body:some View{List(store.phrases){p in VStack(alignment:.leading,spacing:6){HStack{Text(p.english).font(.headline);Spacer();Button{speech.speak(p.english,accent:store.settings.accent)}label:{Image(systemName:"speaker.wave.2.fill")}};Text(p.chinese);Text(p.example).font(.caption).foregroundStyle(.secondary)}}.navigationTitle("片語學習")}}

struct QuizSetupView:View{@EnvironmentObject var store:AppStore;let start:(Int,QuizMode)->Void;@State private var count=20;@State private var mode:QuizMode = .englishToChinese;var body:some View{Form{Section("測驗模式"){Picker("模式",selection:$mode){ForEach(QuizMode.allCases){Text($0.rawValue).tag($0)}}};Section("題數"){Picker("題數",selection:$count){ForEach([10,20,40],id:\.self){Text("\($0) 題").tag($0)}}.pickerStyle(.segmented)};Section{Button("開始測驗"){start(count,mode)}.frame(maxWidth:.infinity)}}.navigationTitle("測驗設定")}}
struct QuizView:View{@EnvironmentObject var store:AppStore;@EnvironmentObject var speech:SpeechService;let done:()->Void;@State private var selected:Int?;@State private var result:AnswerRecord?;var q:QuizQuestion?{store.questions.indices.contains(store.currentIndex) ? store.questions[store.currentIndex]:nil};var body:some View{ScrollView{if let q{VStack(spacing:16){HStack{Text("第 \(store.currentIndex+1) / \(store.questions.count) 題").bold();Spacer();Text(q.type.rawValue).font(.caption).padding(7).background(PLColor.purpleSoft).clipShape(Capsule())};ProgressView(value:Double(store.currentIndex+1),total:Double(store.questions.count));Text(q.type == .listening ? "🔊 聽音選答案":q.prompt).font(.title3.bold()).frame(maxWidth:.infinity,alignment:.leading);if q.type == .listening{Button("播放題目"){speech.speak(q.prompt,accent:store.settings.accent)}};ForEach(q.options.indices,id:\.self){i in Button{if result==nil{selected=i;store.select(i)}}label:{HStack{Text(["A","B","C","D"][min(i,3)]+". "+q.options[i]);Spacer();if let r=result{if i==q.correctIndex{Image(systemName:"checkmark.circle.fill").foregroundStyle(.green)}else if i==selected && !r.isCorrect{Image(systemName:"xmark.circle.fill").foregroundStyle(.red)}}}.frame(maxWidth:.infinity,alignment:.leading).padding().background(optionColor(i,q)).clipShape(RoundedRectangle(cornerRadius:14))}.buttonStyle(.plain)};if let r=result{VStack(alignment:.leading,spacing:6){Text(r.isCorrect ? "答對了！":"答錯了").font(.headline).foregroundStyle(r.isCorrect ? .green:.red);Text("正確答案：\(r.correctAnswer)");if store.settings.showExplanation{Text(r.explanation).font(.subheadline)}}.frame(maxWidth:.infinity,alignment:.leading).cardStyle();Button(store.currentIndex==store.questions.count-1 ? "查看結果":"下一題"){if store.next(){selected=nil;result=nil;if store.settings.autoReadQuestion, let nq=self.q{speech.speak(nq.prompt,accent:store.settings.accent)}}else{done()}}.buttonStyle(.borderedProminent).frame(maxWidth:.infinity)}else{Button("確認答案"){if let s=selected{result=store.submit(s);if store.settings.soundEffects{result?.isCorrect==true ? SoundFX.correct():SoundFX.wrong()}}}.buttonStyle(.borderedProminent).disabled(selected==nil).frame(maxWidth:.infinity)}}.padding()}}.navigationBarBackButtonHidden()}
    func optionColor(_ i:Int,_ q:QuizQuestion)->Color{guard let r=result else{return selected==i ? PLColor.purpleSoft:Color(.secondarySystemBackground)};if i==q.correctIndex{return .green.opacity(0.18)};if i==selected && !r.isCorrect{return .red.opacity(0.16)};return Color(.secondarySystemBackground)} }
struct ResultView:View{@EnvironmentObject var store:AppStore;let retry:()->Void;var s:QuizSession?{store.completedSession};var body:some View{ScrollView{VStack(spacing:16){Text("測驗完成！").font(.largeTitle.bold());if let s{Text("\(s.score) 分").font(.system(size:56,weight:.black));Text("答對 \(s.correctCount) / \(s.questionCount) 題");ForEach(s.answers){a in VStack(alignment:.leading){Text(a.prompt).bold();Text(a.isCorrect ? "✓ \(a.correctAnswer)":"✗ 你的答案：\(a.selectedAnswer)\n正確：\(a.correctAnswer)").foregroundStyle(a.isCorrect ? .green:.red)}.frame(maxWidth:.infinity,alignment:.leading).cardStyle()};Button("再測一次",action:retry).buttonStyle(.borderedProminent)}}.padding()}.navigationTitle("測驗結果")}}

struct ListeningSetupView:View{let openPractice:()->Void;let startQuiz:(Int)->Void;@State var count=20;var body:some View{Form{Section{Button("進入聽力練習",action:openPractice)};Section("聽力測驗題數"){Picker("題數",selection:$count){ForEach([10,20,40],id:\.self){Text("\($0) 題").tag($0)}}.pickerStyle(.segmented);Button("開始聽力測驗"){startQuiz(count)}}}.navigationTitle("聽力")}}
struct ListeningPracticeView:View{@EnvironmentObject var store:AppStore;@EnvironmentObject var speech:SpeechService;@State var index=0;@State var show=false;var word:Word?{store.words.isEmpty ? nil:store.words[index % store.words.count]};var body:some View{VStack(spacing:18){Text("先聽發音，再確認答案。").foregroundStyle(.secondary);if let w=word{VStack(spacing:14){Button("🔊 播放"){speech.speak(w.english,accent:store.settings.accent,rate:0.88)}.buttonStyle(.borderedProminent);if show{Text(w.english).font(.largeTitle.bold());Text(w.chinese).font(.title3)}else{Button("顯示答案"){show=true}.buttonStyle(.bordered)};Button("下一個"){index=Int.random(in:0..<max(1,store.words.count));show=false}.buttonStyle(.bordered)}.cardStyle(PLColor.purpleSoft)}}.padding().navigationTitle("聽力練習")}}

struct SpeakingView:View{@EnvironmentObject var store:AppStore;@EnvironmentObject var speech:SpeechService;@State private var target="";@State private var accent="美式";@State private var score:Int?;@State private var autoStart=false;var body:some View{ScrollView{VStack(spacing:16){Text(target).font(.title.bold()).multilineTextAlignment(.center).frame(maxWidth:.infinity);Picker("口音",selection:$accent){Text("美式").tag("美式");Text("英式").tag("英式")}.pickerStyle(.segmented);Button("🔊 播放示範"){speech.speak(target,accent:accent,rate:store.settings.speechRate);autoStart=true}.buttonStyle(.borderedProminent);Button(speech.isListening ? "停止錄音":"🎤 開始口說測驗"){Task{if speech.isListening{speech.stopRecognition();grade()}else{await speech.startRecognition(accent:accent)}}}.buttonStyle(.borderedProminent);if !speech.recognizedText.isEmpty{Text("辨識：\(speech.recognizedText)")};if let score{Text("本次分數：\(score) 分").font(.title2.bold())};Button("下一題"){newTarget()}.buttonStyle(.bordered);Divider();Text("最近紀錄").font(.headline).frame(maxWidth:.infinity,alignment:.leading);ForEach(store.speakingRecords.prefix(10)){r in HStack{VStack(alignment:.leading){Text(r.targetText).bold();Text(r.recognizedText).font(.caption)};Spacer();Text("\(r.score)").font(.title3.bold())}.cardStyle()}}.padding()}.navigationTitle("口說測驗").onAppear{if target.isEmpty{newTarget()}}.onChange(of:speech.speechFinished){_,finished in if finished && autoStart{autoStart=false;Task{try? await Task.sleep(for:.milliseconds(500));await speech.startRecognition(accent:accent)}}}}
    func newTarget(){let pool=store.words.shuffled().prefix(100).map{$0.english}+store.phrases.map{$0.english};target=pool.randomElement() ?? "Hello";score=nil;speech.recognizedText=""}
    func grade(){let s=SpeechService.score(target:target,recognized:speech.recognizedText);score=s;store.addSpeaking(target:target,recognized:speech.recognizedText,score:s,accent:accent)} }

struct ReadingListView:View{@EnvironmentObject var store:AppStore;let open:(Int)->Void;var body:some View{List(store.readings){p in Button{open(p.id)}label:{VStack(alignment:.leading){Text(p.title).font(.headline);Text(p.category).font(.caption).foregroundStyle(.secondary);Text("\(p.questions.count) 題").font(.caption)}}}.navigationTitle("閱讀測驗")}}
struct ReadingDetailView:View{@EnvironmentObject var store:AppStore;let passage:ReadingPassage;@State var answers:[Int:Int]=[:];@State var submitted=false;var body:some View{ScrollView{VStack(alignment:.leading,spacing:16){Text(passage.title).font(.title.bold());Text(passage.content).lineSpacing(6).cardStyle();ForEach(passage.questions.indices,id:\.self){qi in let q=passage.questions[qi];VStack(alignment:.leading,spacing:8){Text("\(qi+1). \(q.prompt)").bold();ForEach(q.options.indices,id:\.self){i in Button{if !submitted{answers[qi]=i}}label:{HStack{Image(systemName:answers[qi]==i ? "largecircle.fill.circle":"circle");Text(q.options[i]);Spacer();if submitted && i==q.correctIndex{Image(systemName:"checkmark").foregroundStyle(.green)}}.padding(10).background(submitted && i==q.correctIndex ? Color.green.opacity(0.12):Color(.secondarySystemBackground)).clipShape(RoundedRectangle(cornerRadius:12))}.buttonStyle(.plain)};if submitted{Text(q.explanation).font(.caption).foregroundStyle(.secondary)}}.cardStyle()};Button(submitted ? "重新作答":"送出答案"){if submitted{answers=[:];submitted=false}else{submitted=true}}.buttonStyle(.borderedProminent).frame(maxWidth:.infinity)}.padding()}.navigationTitle("閱讀")}}

struct FavoritesView:View{@EnvironmentObject var store:AppStore;@EnvironmentObject var speech:SpeechService;var items:[Word]{store.words.filter{store.favorites.contains($0.id)}};var body:some View{List(items){w in HStack{VStack(alignment:.leading){Text(w.english).bold();Text(w.chinese)};Spacer();Button{speech.speak(w.english,accent:store.settings.accent)}label:{Image(systemName:"speaker.wave.2")};Button{store.toggleFavorite(w.id)}label:{Image(systemName:"heart.fill")}}}.navigationTitle("收藏單字")}}
struct WrongAnswersView:View{@EnvironmentObject var store:AppStore;var body:some View{List{ForEach(store.wrongAnswers){w in VStack(alignment:.leading,spacing:5){Text(w.prompt).bold();Text("你的答案：\(w.selectedAnswer)").foregroundStyle(.red);Text("正確答案：\(w.correctAnswer)").foregroundStyle(.green);Text(w.explanation).font(.caption);Text("錯誤 \(w.wrongCount) 次").font(.caption2).foregroundStyle(.secondary)}}.onDelete{idx in store.wrongAnswers.remove(atOffsets:idx)}}.navigationTitle("錯題本").toolbar{if !store.wrongAnswers.isEmpty{Button("清除"){store.wrongAnswers=[]}}}}}
struct NotesView:View{@EnvironmentObject var store:AppStore;@State var title="";@State var content="";var body:some View{List{Section("新增筆記"){TextField("標題",text:$title);TextField("內容",text:$content,axis:.vertical);Button("加入"){guard !title.isEmpty else{return};store.notes.insert(StudyNote(key:UUID().uuidString,category:"自訂",kind:"note",title:title,content:content),at:0);title="";content=""}};Section("筆記"){ForEach(store.notes){n in VStack(alignment:.leading){Text(n.title).bold();Text(n.content)}}.onDelete{store.notes.remove(atOffsets:$0)}}}.navigationTitle("學習筆記")}}
struct HistoryView:View{@EnvironmentObject var store:AppStore;var body:some View{List{ForEach(store.sessions){s in VStack(alignment:.leading){HStack{Text(s.modeLabel).bold();Spacer();Text("\(s.score) 分").font(.headline)};Text("\(s.correctCount)/\(s.questionCount) 題 ・ \(s.finishedAt.formatted(date:.abbreviated,time:.shortened))").font(.caption).foregroundStyle(.secondary)}}.onDelete{store.sessions.remove(atOffsets:$0)}}.navigationTitle("學習紀錄")}}
struct AnalyticsView:View{@EnvironmentObject var store:AppStore;var avg:Int{store.sessions.isEmpty ? 0:store.sessions.map{$0.score}.reduce(0,+)/store.sessions.count};var accuracy:Double{let all=store.sessions.flatMap{$0.answers};return all.isEmpty ? 0:Double(all.filter{$0.isCorrect}.count)/Double(all.count)};var body:some View{ScrollView{VStack(spacing:14){Text("學習分析").font(.largeTitle.bold()).frame(maxWidth:.infinity,alignment:.leading);HStack{StatCard("平均分數","\(avg)","chart.bar.fill");StatCard("總測驗","\(store.sessions.count)","checkmark.circle")};HStack{StatCard("總答題","\(store.sessions.reduce(0){$0+$1.questionCount})","number");StatCard("正確率","\(Int(accuracy*100))%","target")};VStack(alignment:.leading){Text("學習建議").font(.headline);Text(accuracy>=0.8 ? "表現穩定，可增加多益模擬題與閱讀題組。":"建議從錯題本與收藏單字開始複習，再進行短題數測驗。")}.frame(maxWidth:.infinity,alignment:.leading).cardStyle()}.padding()}.navigationTitle("")}}
struct StatCard:View{let a:String,b:String,i:String;init(_ a:String,_ b:String,_ i:String){self.a=a;self.b=b;self.i=i};var body:some View{VStack{Image(systemName:i);Text(b).font(.title.bold());Text(a).font(.caption)}.frame(maxWidth:.infinity).cardStyle()}}
struct DailyMissionView:View{@EnvironmentObject var store:AppStore;var body:some View{VStack(spacing:20){Image(systemName:"medal.fill").font(.system(size:70)).foregroundStyle(.orange);Text("今日任務（成人版）").font(.title.bold());Text("完成 20 題可獲得獎勵！");ProgressView(value:Double(min(store.todayAnswered,20)),total:20);Text("\(min(store.todayAnswered,20)) / 20").font(.title2.bold());if store.todayAnswered>=20{Text("🎉 今日任務完成！").font(.title3.bold()).foregroundStyle(.green)}}.padding().navigationTitle("每日任務")}}
struct AchievementsView:View{@EnvironmentObject var store:AppStore;var body:some View{List{Achievement("初次挑戰","完成第一份測驗",store.sessions.count>=1);Achievement("持續學習","完成 10 份測驗",store.sessions.count>=10);Achievement("收藏家","收藏 20 個單字",store.favorites.count>=20);Achievement("口說練習家","完成 10 次口說",store.speakingRecords.count>=10)}.navigationTitle("成就")}}
struct Achievement:View{let a:String,b:String,done:Bool;init(_ a:String,_ b:String,_ done:Bool){self.a=a;self.b=b;self.done=done};var body:some View{HStack{Image(systemName:done ? "trophy.fill":"lock.fill").foregroundStyle(done ? .orange:.secondary);VStack(alignment:.leading){Text(a).bold();Text(b).font(.caption).foregroundStyle(.secondary)};Spacer();if done{Text("已完成").foregroundStyle(.green)}}}}
struct SettingsView:View{@EnvironmentObject var store:AppStore;var body:some View{Form{Section("發音"){Picker("口音",selection:$store.settings.accent){Text("美式").tag("美式");Text("英式").tag("英式")};HStack{Text("語速");Slider(value:$store.settings.speechRate,in:0.7...1.3);Text(String(format:"%.1fx",store.settings.speechRate))}};Section("測驗"){Toggle("音效",isOn:$store.settings.soundEffects);Toggle("自動朗讀題目",isOn:$store.settings.autoReadQuestion);Toggle("顯示解析",isOn:$store.settings.showExplanation);Toggle("自動加入錯題本",isOn:$store.settings.addWrongAnswerAutomatically);Stepper("每日目標：\(store.settings.dailyGoal) 題",value:$store.settings.dailyGoal,in:5...100,step:5)};Section("顯示"){Picker("主題",selection:$store.settings.themeMode){Text("淺色").tag("淺色");Text("深色").tag("深色");Text("跟隨系統").tag("系統")};Toggle("大字體",isOn:$store.settings.largeText)};Section{Button("重設設定",role:.destructive){store.resetSettings()}}}.navigationTitle("設定")}}
